# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("backups", command=peewee.CharField(default=""))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("backups", ["command"])
    """
    Write your rollback migrations here.
    """
